import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

from tools.gcode_compare import normalize_gcode_text, semantic_summary


class GcodeCompareTests(unittest.TestCase):
    def test_normalize_removes_non_deterministic_comments_but_keeps_commands(self):
        text = "\n".join(
            [
                "; generated by OrcaSlicer 2.3.0 on 2026-06-26 at 12:34:56",
                "; output file: C:\\Users\\me\\AppData\\Local\\Temp\\part.gcode",
                "; thumbnail begin 32x32 1234",
                "; iVBORw0KGgoAAAANSUhEUgAAAAEAAAAB",
                "; thumbnail end",
                ";LAYER_CHANGE",
                ";Z:0.2",
                "G1 X10.0 Y20.0 E0.12345 F1800",
                "M104 S220",
            ]
        )

        normalized = normalize_gcode_text(text)

        self.assertNotIn("; generated by OrcaSlicer 2.3.0 on 2026-06-26 at 12:34:56", normalized)
        self.assertNotIn("; output file: C:\\Users\\me\\AppData\\Local\\Temp\\part.gcode", normalized)
        self.assertNotIn("; iVBORw0KGgoAAAANSUhEUgAAAAEAAAAB", normalized)
        self.assertIn(";LAYER_CHANGE", normalized)
        self.assertIn("G1 X10.0 Y20.0 E0.12345 F1800", normalized)
        self.assertIn("M104 S220", normalized)

    def test_semantic_summary_counts_layers_commands_and_extrusion(self):
        lines = [
            ";LAYER_CHANGE",
            "G1 X1 Y1 F1200",
            "G1 X2 Y2 E0.5000 F1800",
            "M104 S220",
            ";LAYER_CHANGE",
            "G1 X3 Y3 E1.2500",
            "M140 S65",
        ]

        summary = semantic_summary(lines)

        self.assertEqual(summary["layer_changes"], 2)
        self.assertEqual(summary["commands"]["G1"], 3)
        self.assertEqual(summary["commands"]["M104"], 1)
        self.assertEqual(summary["commands"]["M140"], 1)
        self.assertAlmostEqual(summary["total_e"], 1.75)
        self.assertEqual(summary["temperature_commands"], ["M104 S220", "M140 S65"])

    def test_cli_writes_report_with_normalized_equality(self):
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            expected = tmp_path / "expected.gcode"
            actual = tmp_path / "actual.gcode"
            report = tmp_path / "report.json"

            expected.write_text(
                "; generated by OrcaSlicer on Friday\n;LAYER_CHANGE\nG1 X1 E0.1\n",
                encoding="utf-8",
            )
            actual.write_text(
                "; generated by OWzx on Saturday\n;LAYER_CHANGE\nG1 X1 E0.1\n",
                encoding="utf-8",
            )

            proc = subprocess.run(
                [
                    sys.executable,
                    "tools/gcode_compare.py",
                    "--expected",
                    str(expected),
                    "--actual",
                    str(actual),
                    "--report",
                    str(report),
                ],
                cwd=Path(__file__).resolve().parents[2],
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )

            self.assertEqual(proc.returncode, 0, proc.stderr)
            data = json.loads(report.read_text(encoding="utf-8"))
            self.assertFalse(data["raw_equal"])
            self.assertTrue(data["normalized_equal"])
            self.assertEqual(data["normalized_diff"], [])


if __name__ == "__main__":
    unittest.main()
