#include "AppTheme.h"

namespace AppTheme
{

  QString mainStyleSheet()
  {
    return QStringLiteral(
        "QWidget#MainWindow {"
        "  background: transparent;"
        "}"
        "QFrame#RootPanel {"
        "  background: #1f2228;"
        "  border: 1px solid #262b33;"
        "  border-radius: 0px;"
        "}"
        "QFrame#TitleBar {"
        "  background: #0d0f12;"
        "  border: none;"
        "  border-top-left-radius: 0px;"
        "  border-top-right-radius: 0px;"
        "}"
        "QFrame#QuickBar, QFrame#StatusBar {"
        "  background: #232831;"
        "  border: none;"
        "}"
        "QFrame#PrepareTopToolBar {"
        "  background: #2a2f37;"
        "  border-top: 1px solid #373d47;"
        "  border-bottom: 1px solid #313742;"
        "}"
        "QFrame#PageBody, QFrame#SidePanel, QFrame#MainPanel {"
        "  background: #252b34;"
        "  border: none;"
        "}"
        "QFrame#PrepareLeftPanel {"
        "  background: #2a2f36;"
        "  border-right: 1px solid #3a414c;"
        "}"
        "QFrame#PrepareCenterPanel {"
        "  background: #2f3138;"
        "}"
        "QFrame#PrepareRightPanel {"
        "  background: #2b3038;"
        "  border-left: 1px solid #3b4452;"
        "}"
        "QFrame#PrepareViewport {"
        "  background: #383b43;"
        "  border: 1px solid #424852;"
        "  border-radius: 4px;"
        "}"
        "QFrame#MaterialHeader {"
        "  background: #5fd139;"
        "  border: none;"
        "}"
        "QFrame#PrepareParamBody {"
        "  background: #4a4e56;"
        "}"
        "QFrame#DeviceTopBar {"
        "  background: #171a20;"
        "  border-bottom: 1px solid #2a3038;"
        "}"
        "QFrame#DevicePanel {"
        "  background: #0e1116;"
        "}"
        "QFrame#DeviceInnerBar {"
        "  background: #20242b;"
        "  border: 1px solid #2f3640;"
        "}"
        "QFrame#DeviceListHeader {"
        "  background: #1b2027;"
        "  border: 1px solid #2a3039;"
        "  border-top: none;"
        "}"
        "QFrame#DeviceEmptyArea {"
        "  background: #1a1d23;"
        "  border: 1px solid #2a3039;"
        "  border-top: none;"
        "}"
        "QFrame#SettingsCard {"
        "  background: #474c55;"
        "  border-top: 1px solid #5a616e;"
        "}"
        "QFrame#ViewportSurface {"
        "  background: #171b21;"
        "  border: 1px solid #39414c;"
        "  border-radius: 6px;"
        "}"
        "QFrame#InfoCard {"
        "  background: #2a313c;"
        "  border: 1px solid #3b4657;"
        "  border-radius: 6px;"
        "}"
        "QPushButton, QToolButton {"
        "  border: none;"
        "  border-radius: 4px;"
        "  padding: 6px 10px;"
        "  color: #dfe6ef;"
        "  background: #39414c;"
        "}"
        "QPushButton:pressed, QToolButton:pressed {"
        "  background: #2f3640;"
        "}"
        "QPushButton:disabled, QToolButton:disabled {"
        "  background: #2a3038;"
        "  color: #8792a1;"
        "}"
        "QPushButton:hover, QToolButton:hover {"
        "  background: #4a5564;"
        "}"
        "QPushButton#PrimaryBtn {"
        "  background: #2f69d8;"
        "  color: #ffffff;"
        "  font-weight: 600;"
        "}"
        "QPushButton#PrimaryBtn:hover {"
        "  background: #3d78ea;"
        "}"
        "QPushButton#PrimaryBtn:pressed {"
        "  background: #2759ba;"
        "}"
        "QPushButton#MiniTag {"
        "  background: #3b434f;"
        "  border: 1px solid #505a68;"
        "  padding: 3px 8px;"
        "  border-radius: 3px;"
        "}"
        "QPushButton#MiniTag:hover {"
        "  background: #485364;"
        "}"
        "QLabel#PreviewThumbIndex {"
        "  background: #3f2b2b;"
        "  border: 1px solid #00d36c;"
        "  color: #dde4ef;"
        "  padding: 4px;"
        "}"
        "QPushButton#CloseBtn:hover, QToolButton#CloseBtn:hover {"
        "  background: #d35656;"
        "  color: #ffffff;"
        "}"
        "QToolButton#RoundTool {"
        "  border-radius: 14px;"
        "  background: #545a64;"
        "  color: #dbe2eb;"
        "}"
        "QToolButton#RoundTool:hover {"
        "  background: #697180;"
        "}"
        "QPushButton#NavBtn[active=\"true\"] {"
        "  background: #4a78c8;"
        "  color: #ffffff;"
        "}"
        "QLabel {"
        "  color: #dfe6ef;"
        "}"
        "QLabel#SectionTitle {"
        "  color: #ffffff;"
        "  font-weight: 600;"
        "}"
        "QLabel#ViewHint {"
        "  color: #cdd5e2;"
        "  background: #5f6672;"
        "  border-radius: 3px;"
        "  padding: 4px 6px;"
        "}"
        "QLabel#MutedText {"
        "  color: #9eabba;"
        "}"
        "QListWidget, QTreeWidget, QTabWidget::pane, QTableWidget {"
        "  background: #20252d;"
        "  border: 1px solid #3a434f;"
        "  color: #d5dde8;"
        "}"
        "QListWidget::item:selected, QTreeWidget::item:selected {"
        "  background: #3a4d72;"
        "  color: #ffffff;"
        "}"
        "QTableWidget::item:selected {"
        "  background: #3a4d72;"
        "}"
        "QHeaderView::section {"
        "  background: #303845;"
        "  color: #d5dde8;"
        "  border: none;"
        "  padding: 6px;"
        "}"
        "QTabBar::tab {"
        "  background: #303845;"
        "  color: #d5dde8;"
        "  border: none;"
        "  padding: 6px 10px;"
        "  margin-right: 1px;"
        "}"
        "QTabBar::tab:selected {"
        "  background: #4a78c8;"
        "  color: white;"
        "}"
        "QComboBox {"
        "  background: #2d3642;"
        "  border: 1px solid #435061;"
        "  border-radius: 4px;"
        "  color: #dfe6ef;"
        "  padding: 4px 6px;"
        "}"
        "QLineEdit {"
        "  background: #2d3642;"
        "  border: 1px solid #435061;"
        "  border-radius: 4px;"
        "  color: #dfe6ef;"
        "  padding: 5px 8px;"
        "}"
        "QProgressBar {"
        "  border: 1px solid #425066;"
        "  border-radius: 4px;"
        "  background: #20252d;"
        "  text-align: center;"
        "  color: #d5dde8;"
        "}"
        "QProgressBar::chunk {"
        "  background: #2f69d8;"
        "  border-radius: 3px;"
        "}"
        "QScrollBar:vertical {"
        "  background: #232831;"
        "  width: 10px;"
        "  margin: 0;"
        "}"
        "QScrollBar::handle:vertical {"
        "  background: #465366;"
        "  border-radius: 4px;"
        "  min-height: 20px;"
        "}"
        "QScrollBar:horizontal {"
        "  background: #232831;"
        "  height: 10px;"
        "  margin: 0;"
        "}"
        "QScrollBar::handle:horizontal {"
        "  background: #465366;"
        "  border-radius: 4px;"
        "  min-width: 20px;"
        "}");
  }

} // namespace AppTheme
