"""Fill English translations into en.ts"""
import re, sys, html

TRANSLATIONS = {
    "❓  关于 Creality Print": "❓  About Creality Print",
    "版本 7.0.0.0  (Qt6 QML 重写)": "Version 7.0.0.0  (Qt6 QML Rewrite)",
    "Qt 版本": "Qt Version",
    "QML 引擎": "QML Engine",
    "构建类型": "Build Type",
    "目标平台": "Target Platform",
    "构建日期": "Build Date",
    "开源协议": "Open Source License",
    "官方网站": "Official Website",
    "本软件基于 Qt 6 框架构建，遵循 GNU LGPL v3 协议。使用本软件即代表您同意\n相关使用条款。": "This software is built on the Qt 6 framework under GNU LGPL v3. Using this software indicates acceptance of the relevant terms.",
    "本软件基于 Qt 6 框架构建，遵循 GNU LGPL v3 协议。使用本软件即代表您同意 \n相关使用条款。": "This software is built on the Qt 6 framework under GNU LGPL v3. Using this software indicates acceptance of the relevant terms.",
    "确认": "OK",
    "辅助功能": "Auxiliary Tools",
    "提供打印辅助分析和工具": "Print analysis and auxiliary tools",
    "模型分析": "Model Analysis",
    "检查模型几何问题": "Check model geometry issues",
    "支撑预览": "Support Preview",
    "查看支撑结构分布": "View support structure distribution",
    "尺寸标注": "Dimension Annotation",
    "精确测量模型尺寸": "Measure model dimensions precisely",
    "颜色分区": "Color Partition",
    "多色打印分区工具": "Multi-color print partition tool",
    "重量估算": "Weight Estimation",
    "预估耗材用量": "Estimate filament usage",
    "对称工具": "Symmetry Tool",
    "模型镜像与对称操作": "Mirror and symmetry operations",
    "模型切割": "Model Cut",
    "切割大型模型分部打印": "Cut large models for part printing",
    "层预览": "Layer Preview",
    "逐层查看切片结果": "View slice results layer by layer",
    "打印报告": "Print Report",
    "生成详细打印分析报告": "Generate detailed print analysis report",
    "校准": "Calibration",
    "校准进行中，请勿移动打印机…": "Calibration in progress, do not move the printer…",
    "校准完成！": "Calibration complete!",
    "准备开始校准": "Ready to start calibration",
    "进度": "Progress",
    "✕ 取消": "✕ Cancel",
    "完成": "Done",
    "开始": "Start",
    "校准中心": "Calibration Center",
    "选择左侧校准项目开始": "Select a calibration item on the left to begin",
    "开始校准": "Start Calibration",
    "重置参数": "Reset Parameters",
    "首层校准": "First Layer Calibration",
    "调整首层高度": "Adjust first layer height",
    "精确调整首层打印高度，确保良好附着。": "Precisely adjust the first layer print height to ensure good adhesion.",
    "首层高度预览区": "First Layer Height Preview",
    "热床校正": "Bed PID Tuning",
    "PID 热床温度校正": "PID Bed Temperature Tuning",
    "校正热床 PID 参数，稳定床温。": "Tune bed PID parameters to stabilize bed temperature.",
    "温度曲线图": "Temperature Graph",
    "共振补偿": "Resonance Compensation",
    "输入整形/共振测试": "Input Shaping / Resonance Test",
    "测量并补偿打印机共振以提升质量。": "Measure and compensate printer resonance to improve quality.",
    "频率响应图": "Frequency Response Graph",
    "流量校准": "Flow Calibration",
    "挤出流量线性校准": "Linear Extrusion Flow Calibration",
    "校准挤出机流量，减少欠挤或过挤。": "Calibrate extruder flow to reduce under/over extrusion.",
    "测试块预览": "Test Block Preview",
    "速度校准": "Speed Calibration",
    "最大速度测试": "Max Speed Test",
    "测试各轴最大速度与加速度边界。": "Test maximum speed and acceleration limits for each axis.",
    "速度斜坡图": "Speed Ramp Graph",
    "喷嘴偏移": "Nozzle Offset",
    "XY 喷嘴偏移校准": "XY Nozzle Offset Calibration",
    "多喷头打印机的喷嘴偏移精确对齐。": "Precise nozzle offset alignment for multi-extruder printers.",
    "偏移测试图案": "Offset Test Pattern",
    "压力提前": "Pressure Advance",
    "Linear Advance 校准": "Linear Advance Calibration",
    "校准压力提前参数，消除拐角鼓包。": "Calibrate pressure advance to eliminate corner bulging.",
    "折线测试图": "Line Test Pattern",
    "层高": "Layer Height",
    "质量": "Quality",
    "首层层高": "First Layer Height",
    "线宽": "Line Width",
    "壁线圈数": "Wall Line Count",
    "顶层层数": "Top Layers",
    "底层层数": "Bottom Layers",
    "填充密度 (%)": "Infill Density (%)",
    "填充": "Infill",
    "填充图案": "Infill Pattern",
    "网格": "Grid",
    "直线": "Lines",
    "三角": "Triangles",
    "蜂巢": "Honeycomb",
    "陀螺": "Gyroid",
    "填充重叠 (%)": "Infill Overlap (%)",
    "打印速度 (mm/s)": "Print Speed (mm/s)",
    "速度": "Speed",
    "空走速度 (mm/s)": "Travel Speed (mm/s)",
    "首层速度 (mm/s)": "First Layer Speed (mm/s)",
    "外壁速度 (mm/s)": "Outer Wall Speed (mm/s)",
    "喷嘴温度 (°C)": "Nozzle Temperature (°C)",
    "温度": "Temperature",
    "热床温度 (°C)": "Bed Temperature (°C)",
    "腔体温度 (°C)": "Chamber Temperature (°C)",
    "预热时间 (s)": "Preheat Time (s)",
    "启用支撑": "Enable Support",
    "支撑": "Support",
    "支撑密度 (%)": "Support Density (%)",
    "支撑类型": "Support Type",
    "普通": "Normal",
    "树状": "Tree",
    "启用 Brim": "Enable Brim",
    "底座": "Adhesion",
    "Brim 宽度 (mm)": "Brim Width (mm)",
    "裙边线数": "Skirt Line Count",
    "风扇速度 (%)": "Fan Speed (%)",
    "冷却": "Cooling",
    "风扇延迟 (层)": "Fan Delay (layers)",
    "启用回退": "Enable Retraction",
    "回退": "Retraction",
    "回退距离 (mm)": "Retraction Distance (mm)",
    "回退速度 (mm/s)": "Retraction Speed (mm/s)",
    "Z 缝策略": "Z Seam Strategy",
    "最锐角": "Sharpest Corner",
    "最短": "Shortest",
    "随机": "Random",
    "指定": "Specified",
    "其他": "Other",
    "启用 Coasting": "Enable Coasting",
    "设备列表": "Device List",
    "+ 添加设备": "+ Add Device",
    "设备名称": "Device Name",
    "设备型号": "Device Model",
    "状态": "Status",
    "最近打印": "Last Print",
    "设备 ": "Device ",
    "在线": "Online",
    "离线": "Offline",
    "未发现设备": "No devices found",
    "就绪": "Ready",
    "关闭": "Close",
    "专业级 3D 打印切片软件": "Professional 3D Print Slicing Software",
    "登录账号": "Sign In",
    "最近项目": "Recent Projects",
    "项目 ": "Project ",
    "快速入口": "Quick Access",
    "打开项目": "Open Project",
    "打开已有 3MF/STL 文件": "Open existing 3MF/STL file",
    "新建项目": "New Project",
    "从空白开始创建": "Create from scratch",
    "打印机校准向导": "Printer Calibration Wizard",
    "模型商城": "Model Mall",
    "在线下载模型": "Download models online",
    "版本 7.0.0  |  Qt 6.10  |  ©2026 Creality": "Version 7.0.0  |  Qt 6.10  |  ©2026 Creality",
    "搜索模型…": "Search models…",
    "推荐": "Featured",
    "热门": "Popular",
    "最新": "Latest",
    "免费": "Free",
    "全部": "All",
    "家居": "Home",
    "玩具": "Toys",
    "工具": "Tools",
    "艺术": "Art",
    "教育": "Education",
    "珠宝": "Jewelry",
    "运动": "Sports",
    "3D 模型 #": "3D Model #",
    "多机打印": "Multi-Machine Print",
    "发送到全部": "Send to All",
    "任务队列": "Task Queue",
    "打印机 ": "Printer ",
    "空闲": "Idle",
    "发送": "Send",
    "暂停": "Pause",
    "停止": "Stop",
    "暂无任务": "No tasks",
    "对象列表": "Object List",
    " 个": " objects",
    "场景中无对象": "No objects in scene",
    "+ 导入模型": "+ Import Model",
    "外观": "Appearance",
    "语言": "Language",
    "快捷键": "Shortcuts",
    "打印机": "Printer",
    "账号与隐私": "Account & Privacy",
    "更新": "Updates",
    "高级": "Advanced",
    "关于": "About",
    "界面主题": "UI Theme",
    "深色 (默认)": "Dark (Default)",
    "深蓝": "Deep Blue",
    "极暗": "Ultra Dark",
    "字体大小": "Font Size",
    "界面缩放": "UI Scale",
    "简体中文": "Simplified Chinese",
    "恢复默认": "Reset to Default",
    "应用": "Apply",
    "✓ 已实时生效": "✓ Applied",
    # 导航标签（main.qml）
    "主页": "Home",
    "准备": "Prepare",
    "预览": "Preview",
    "设备": "Devices",
    "项目": "Project",
    "辅助": "Auxiliary",
    "偏好": "Preferences",
    "多机": "Multi-Machine",
    "参数设置": "Settings",
    "光面PEI板/涂层板": "Smooth PEI / Coated Plate",
    "普通PEI板": "Standard PEI Plate",
    "对象": "Objects",
    "切片角色": "Slice Role",
    "发送打印": "Send to Print",
    "0.20mm 标准 @Creality K1C": "0.20mm Standard @Creality K1C",
    "打印质量": "Print Quality",
    "0.16mm 精细": "0.16mm Fine",
    "0.24mm 草稿": "0.24mm Draft",
    "0.28mm 超草稿": "0.28mm Super Draft",
    "0.12mm 超精细": "0.12mm Ultra Fine",
    "耗材": "Filament",
    "🖨  发送打印": "🖨  Send to Print",
    " 个对象  ·  层高 0.20 mm": " objects  ·  Layer Height 0.20 mm",
    "输出路径": "Output Path",
    "切片后自动发送": "Auto send after slicing",
    "完成后通知": "Notify when done",
    "导出 G-code": "Export G-code",
    "取消": "Cancel",
    "▶ 打印": "▶ Print",
    "质量预设": "Quality Preset",
    "▶ 开始切片": "▶ Start Slice",
    "打开": "Open",
    "保存": "Save",
    "另存为": "Save As",
    "导入模型": "Import Model",
    "导出": "Export",
    "● 未保存": "● Unsaved",
    "项目资源": "Project Resources",
    "选择文件查看详情": "Select a file to view details",
    "属性": "Properties",
    "路径": "Path",
    "格式": "Format",
    "大小": "Size",
    "修改时间": "Modified",
    "无项目": "No Project",
    "未命名项目": "Untitled Project",
    "参数分类": "Parameter Category",
    "← 返回": "← Back",
    " 项": " items",
    "搜索参数名...": "Search parameter...",
    "无匹配参数": "No matching parameters",
    "只读": "Read-only",
    "预设": "Presets",
    "打印": "Print",
    "切片": "Slice",
    "⚙  高级设置": "⚙  Advanced Settings",
    "切片进行中...": "Slicing in progress...",
    "切片完成": "Slice Complete",
    "等待切片": "Waiting to Slice",
    "切片进度": "Slice Progress",
    "预计打印时长": "Estimated Print Time",
    "✕ 取消切片": "✕ Cancel Slice",
    "Prepare": "Prepare",
    "Preview": "Preview",
    "Start Slice": "Start Slice",
    "0.20mm 标准": "0.20mm Standard",
    "0.20mm 精细": "0.20mm Fine",
    "0.30mm 快速": "0.30mm Fast",
    "0.15mm 超精细": "0.15mm Ultra Fine",
}

def fill_translations(ts_path):
    with open(ts_path, encoding="utf-8") as f:
        text = f.read()

    def replacer(m):
        src = m.group(1)
        stripped = src.strip()
        eng = TRANSLATIONS.get(stripped) or TRANSLATIONS.get(src)
        if eng:
            return f"<source>{src}</source>\n        <translation>{html.escape(eng)}</translation>"
        return m.group(0)  # leave unchanged

    # Replace each <source>X</source>\n        <translation type="unfinished">...</translation>
    pattern = re.compile(
        r'<source>(.*?)</source>\s*\n\s*<translation[^>]*>.*?</translation>',
        re.DOTALL
    )
    new_text = pattern.sub(replacer, text)

    with open(ts_path, "w", encoding="utf-8") as f:
        f.write(new_text)

    # Count how many got filled
    filled = sum(1 for src in re.findall(r'<source>(.*?)</source>', new_text, re.DOTALL)
                 if src.strip() in TRANSLATIONS or src in TRANSLATIONS)
    total = len(re.findall(r'<source>', new_text))
    print(f"Filled {filled}/{total} translations")

if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else r"E:\ai\3DPrinter_Qt6\i18n\en.ts"
    fill_translations(path)
    print("Done.")
