#!/usr/bin/env python3
"""Compare G-code generated by upstream OrcaSlicer and OWzx.

The raw files are still hashed and reported, but the automated pass/fail
decision is based on normalized G-code so timestamps, paths, thumbnails, and
other non-deterministic comments do not hide meaningful slicer differences.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import re
import sys
from collections import Counter
from pathlib import Path
from typing import Iterable


NON_DETERMINISTIC_COMMENT_PATTERNS = [
    re.compile(r"^;\s*generated\b", re.IGNORECASE),
    re.compile(r"^;\s*generated\s+by\b", re.IGNORECASE),
    re.compile(r"^;\s*generator\b", re.IGNORECASE),
    re.compile(r"^;\s*generated\s+on\b", re.IGNORECASE),
    re.compile(r"^;\s*date\b", re.IGNORECASE),
    re.compile(r"^;\s*time\b", re.IGNORECASE),
    re.compile(r"^;\s*timestamp\b", re.IGNORECASE),
    re.compile(r"^;\s*output\s*(file|filename|path)\b", re.IGNORECASE),
    re.compile(r"^;\s*file\s*(path|name)\b", re.IGNORECASE),
    re.compile(r"^;\s*source\s*(file|path)\b", re.IGNORECASE),
    re.compile(r"^;\s*estimated\s+(printing\s+)?time\b", re.IGNORECASE),
    re.compile(r"^;\s*total\s+elapsed\s+time\b", re.IGNORECASE),
    re.compile(r"^;\s*filament\s+cost\b", re.IGNORECASE),
    re.compile(r"^;\s*nozzle_temperature\s*=", re.IGNORECASE),
]

ABSOLUTE_PATH_PATTERN = re.compile(r"([A-Za-z]:\\|/home/|/Users/|/tmp/|\\\\)")
COMMAND_PATTERN = re.compile(r"^([GMT]\d+)\b", re.IGNORECASE)
EXTRUSION_PATTERN = re.compile(r"(?:^|\s)E(-?\d+(?:\.\d+)?)\b", re.IGNORECASE)
TEMP_COMMANDS = {"M104", "M109", "M140", "M190", "M141", "M191"}


def _is_thumbnail_begin(line: str) -> bool:
    return bool(re.match(r"^;\s*(thumbnail|png)\s+begin\b", line, re.IGNORECASE))


def _is_thumbnail_end(line: str) -> bool:
    return bool(re.match(r"^;\s*(thumbnail|png)\s+end\b", line, re.IGNORECASE))


def _is_non_deterministic_comment(line: str) -> bool:
    if not line.startswith(";"):
        return False
    if ABSOLUTE_PATH_PATTERN.search(line):
        return True
    return any(pattern.search(line) for pattern in NON_DETERMINISTIC_COMMENT_PATTERNS)


def normalize_gcode_text(text: str) -> list[str]:
    """Return stable G-code lines suitable for exact normalized comparison."""

    normalized: list[str] = []
    in_thumbnail = False

    for raw_line in text.splitlines():
        line = raw_line.rstrip()

        if _is_thumbnail_begin(line):
            in_thumbnail = True
            continue
        if in_thumbnail:
            if _is_thumbnail_end(line):
                in_thumbnail = False
            continue

        if not line.strip():
            continue
        if _is_non_deterministic_comment(line):
            continue

        normalized.append(line)

    return normalized


def _command_name(line: str) -> str | None:
    match = COMMAND_PATTERN.match(line.strip())
    return match.group(1).upper() if match else None


def semantic_summary(lines: Iterable[str]) -> dict[str, object]:
    """Build a compact semantic summary for human triage."""

    command_counts: Counter[str] = Counter()
    layer_changes = 0
    total_e = 0.0
    temperature_commands: list[str] = []

    for line in lines:
        stripped = line.strip()
        if stripped.startswith(";LAYER_CHANGE"):
            layer_changes += 1

        command = _command_name(stripped)
        if command:
            command_counts[command] += 1
            if command in TEMP_COMMANDS:
                temperature_commands.append(stripped)

        for match in EXTRUSION_PATTERN.finditer(stripped):
            total_e += float(match.group(1))

    return {
        "layer_changes": layer_changes,
        "commands": dict(sorted(command_counts.items())),
        "total_e": round(total_e, 6),
        "temperature_commands": temperature_commands,
    }


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def compare_files(expected_path: Path, actual_path: Path) -> dict[str, object]:
    expected_bytes = expected_path.read_bytes()
    actual_bytes = actual_path.read_bytes()
    expected_text = expected_bytes.decode("utf-8", errors="replace")
    actual_text = actual_bytes.decode("utf-8", errors="replace")

    expected_normalized = normalize_gcode_text(expected_text)
    actual_normalized = normalize_gcode_text(actual_text)
    normalized_diff = list(
        difflib.unified_diff(
            expected_normalized,
            actual_normalized,
            fromfile=str(expected_path),
            tofile=str(actual_path),
            lineterm="",
            n=3,
        )
    )

    return {
        "expected": str(expected_path),
        "actual": str(actual_path),
        "expected_sha256": _sha256_bytes(expected_bytes),
        "actual_sha256": _sha256_bytes(actual_bytes),
        "raw_equal": expected_bytes == actual_bytes,
        "normalized_equal": expected_normalized == actual_normalized,
        "expected_normalized_line_count": len(expected_normalized),
        "actual_normalized_line_count": len(actual_normalized),
        "normalized_diff": normalized_diff,
        "expected_summary": semantic_summary(expected_normalized),
        "actual_summary": semantic_summary(actual_normalized),
    }


def _parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare two G-code files.")
    parser.add_argument("--expected", required=True, type=Path, help="Upstream/source-truth G-code path")
    parser.add_argument("--actual", required=True, type=Path, help="OWzx G-code path")
    parser.add_argument("--report", required=True, type=Path, help="JSON report output path")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv or sys.argv[1:])

    if not args.expected.is_file():
        print(f"Expected G-code not found: {args.expected}", file=sys.stderr)
        return 2
    if not args.actual.is_file():
        print(f"Actual G-code not found: {args.actual}", file=sys.stderr)
        return 2

    report = compare_files(args.expected, args.actual)
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2, ensure_ascii=False), encoding="utf-8")

    if report["normalized_equal"]:
        print(f"PASS normalized G-code match: {args.report}")
        return 0

    print(f"FAIL normalized G-code differs: {args.report}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
